name = "Bryan Reese"
github_link = "https://github.com/bryanmr"

roles = [
  "Solutions Architect",
  "Linux Administrator",
  "HPC Administrator",
  "Web Developer",
  "Ethernet Networking Engineer",
  "Storage Networking Engineer",
  "Security Analyst",
  "Sales Engineer",
  "Writer",
  "Thinker",
]

not_roles = [
  "Artist",
  "Designer",
]

summaries = [
  [ "Solutions Architect", "Experienced solutions architect seeking to work on new and challenging projects that provide an opportunity for growth. Supported IBM’s System X hardware and other development teams to provide an optimal experience for customers. Worked extensively and in depth with the whole of IBM Intelligent Cluster hardware and software portfolio.", ],
  [ "Linux Administrator", "I have used Linux as my primary operating system since I was 16. The one immutable characteristic of me is my love of open software and solving problems with it. I have written extensive amounts of shell script for myself and for the companies I have worked for. My preference is to automate every task, so I don't have to do anything twice.", ],
  [ "HPC Administrator", "I spent years in the lab at IBM and weeks at customer sites (including time in Germany) to deploy and maintain large HPC clusters. I am familiar with setting up MPI over InfiniBand and accessing storage over that same network. My favorite project was using my cluster tools to do data engineering in Germany by measuring thermal and power characteristics of nearly 10,000 servers.", ],
  [ "Web Developer", "My original interest in IT was via JavaScript. I spent time automating a video game when I was younger, where the bot scripts were written in JavaScript. I also later became familiar with PHP, CSS, and HTML. I am currently using serverless with statically served webpages as my preferred method of delivering web content.", ],
  [ "Ethernet Networking Engineer", "My point of view on most Ethernet configurations is that they are overly complicated. Until your hosts are counted in the tens of thousands, a simple setup with gateways limiting broadcast domains, VLANs, and possibly OSPF is all you generally need. I am familiar with massive scale networks and small scale, and know when to implement each.", ],
  [ "Storage Networking Engineer", "I have worked extensively with Fibre Channel while employed at Brocade and while in the labs at IBM. Securing data and optimizing performance through concepts like zoning and routing are things I am familiar with.", ],
  ["Sales Engineer", "Sales is a skill that enables you to convince others. My experience as a sales engineer taught me how to know who to convince and how to avoid cognitive traps. I was taught on the Miller-Heiman sales methodology as well as Challenger. I worked with business development, marketing, and on-site sales extensively during my time at Brocade.", ],
  ["Writer", "Writing is something I enjoy and have done throughout my life and career. I have written hundreds of blog posts on various topics, created technical documentation, written white papers, and completed a novella. My writing has been published by Lenovo, IBM, and Brocade. I hope to one day complete a novel I have been working on, but do not want to accept mediocrity.", ],
  ["Thinker", "Understanding how the world works is very important to me. I enjoy topics big and small and know when I am reaching points I can not prove. I focus on epistemology and occassionally metaphysics. I stay away from politics, ethics, and other societal level problems. I have learned to understand what I can not understand, and to question those who have answers to questions that can't be answered.", ],
  ["Security Analyst", "Part of understanding how everything works is learning what can break it or be exploited about it. At Brocade, one of the consistent problems we had within the organization was a lack of knowledge to be applied to understanding CVEs. Since I had spent time working on security, part of my job became analyzing CVEs and discussing security with our OEM partners.", ],
]

[[experience]]
employer = "Self Employed"
roles = [
  "Writer",
  "Thinker",
]
when = "January 2016 - April 2019"
responsibilities = [
  "Wrote 130 blog posts on various topics.",
  "Completed a novella.",
  "Worked on my novel, including a 20 page outline and 10 pages of notes.",
  "Learned philosophy, enabling me to see the world through other people's perspectives.",
]

[[experience]]
employer = "Brocade"
roles = [
  "Sales Engineer",
  "Storage Networking Engineer",
  "Ethernet Networking Engineer",
  "Solutions Architect",
  "Security Analyst",
]
when = "September 2013 - August 2016"
responsibilities = [
  "Provided support and training to Lenovo, IBM, and EMC",
  "Worked on solutions with partners, writing white papers and creating designs",
  "Configured proof of concepts and recreation of field problems in lab",
  "Met with customers to work on RFPs",
  "Provided assessment of CVEs to OEM partners",
  "Created marketing material such as videos",
  "Presented to clients and customers",
]

[[experience]]
employer = "IBM"
roles = [
  "Solutions Architect",
]
when = "July 2012 - September 2013"
responsibilities = [
  "Escalation point for Product Engineering team",
  "Optimized customer configurations",
  "Implemented System X architecture for Big Data and Smart Analytics",
  "Developed solutions for new products to best meet needs for customers",
]

[[experience]]
employer = "IBM"
roles = [
  "HPC Administrator",
  "Linux Administrator",
  "Storage Networking Engineer",
  "Ethernet Networking Engineer",
]
when = "August 2007 - July 2012"
responsibilities = [
  "Develop test cases and validate all possible configurations for IBM’s e1350 cluster product.",
  "Install and configure clusters and run MPI tests, Linpack, storage I/O, network I/O.",
  "Automated and documented procedures for the configuration of clusters for customers",
  "Administer Ethernet switches (Cisco), InfiniBand switches, SAN, Fiber Channel, and xCAT.",
  "Provided third level support and worked with architects to provide easily supportable configurations",
  "Implemented large projects including onsite install of multiple petaFLOP SuperMUC cluster in Germany",
]

[[education]]
school = "Ivy Tech Community College"
where = "Fort Wayne, IN"
when = "2006"
major = "Computer Information Systems"
degree = "Associate in Applied Sciences"

[[skills]]
roles = [
  "Linux Administrator",
]
name = "Operating Systems"
list = [
  "RHEL",
  "SLES",
  "Debian",
  "Ubuntu",
  "Gentoo",
  "Windows 3.11 to 10",
  "DOS",
]

[[skills]]
name = "Cluster Management"
roles = [
  "Linux Administrator",
]
list = [
  "Microsoft HPC Cluster Manager",
  "xCAT",
  "IPMI",
  "Kickstart",
  "PXE",
  "GPFS",
]

[[skills]]
roles = [
  "Linux Administrator",
]
name = "Computer Languages"
list = [
  "HTML",
  "CSS",
  "PHP",
  "Javascript",
  "BASH",
  "LATEX",
  "SQL",
]

[[skills]]
roles = [
  "Linux Administrator",
]
name = "Tools and Daemons"
list = [
  "Apache",
  "BIND",
  "git",
  "SSHD",
  "NFS",
  "CIFS",
  "GCC",
]

[[skills]]
roles = [
  "Linux Administrator",
]
name = "Interconnects"
list = [
  "InfiniBand",
  "Ethernet",
  "Fibre Channel",
  "Myrinet",
]

[[skills]]
roles = [
  "Linux Administrator",
]
name = "Storage"
list = [
  "SAN",
  "iSCSI",
  "FCoE",
  "NAS",
  "LSI",
  "Brocade",
  "QLogic",
  "Emulex",
]

[[certs]]
name = "Brocade Certified Fabric Administrator Gen 5"
date = "February 17, 2014"

[[certs]]
name = "Brocade Certified Network Professional 2012"
date = "December 6, 2013"

[[certs]]
name = "Brocade Certified Fabric Professional 2013"
date = "January 7, 2014"

[[certs]]
name = "Brocade Certified Network Engineer 2012"
date = "November 18, 2013"

[[certs]]
name = "Miller Heiman Certificate in Strategic Selling"
date = "October 13, 2015"

[[certs]]
name = "Microsoft Office Specialist in Access 2002"
date = "May 7, 2004"

[[certs]]
name = "CompTIA Linux+ Certified Professional"
date = "December 16, 2004"

[[certs]]
name = "CompTIA i-Net+ Certified Professional"
date = "May 2, 2006"

[[certs]]
name = "CompTIA A+ Certified Professional"
date = "May 5, 2005"

[[projects]]
name = "Steamy Cats"

[[patents]]
name = "Collaborative route reservation and ranking in high performance computing fabrics"
number = "US9762505B2"
filed = "January 7, 2014"

[[patents]]
name = "Role assignment for servers in a high performance computing system based on measured performance characteristics"
number = "US9692649B2"
filed = "February 26, 2014"

[[patents]]
name = "Positioning autonomous vehicles based on field of view"
number = "US9604642B2"
filed = "April 29, 2014"

[[patents]]
name = "Cooperative reduced power mode suspension for high input/output (‘I/O’) workloads"
number = "US9501128B2"
filed = "October 30, 2013"

[[patents]]
name = "Keyboard, video and mouse switch identifying and displaying nodes experiencing a problem"
number = "US8943373B1"
filed = "September 26, 2013"
